Repository codeit-2000/codeit-resources-2.0, pull requests merged in 2024-11, with the labels that each got.

#3 📦️ Chore(#2): storybook 초기 세팅
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
Labels: 📦️ Chore

#4 📦️ Chore(#1): ESLint 설정 및 Prettier 설정
  .eslintrc.json
  .prettierrc.json
  package.json
Labels: 📦️ Chore

#8 📦️ Chore(#5): svgr 세팅
  next.config.ts
  package.json
  pnpm-lock.yaml
  svgr.d.ts
  tsconfig.json
Labels: 📦️ Chore

#12 📦 Chore(#6): 백엔드 세팅
  .gitignore
  amplify/auth/resource.ts
  amplify/backend.ts
  amplify/data/resource.ts
  amplify/package.json
  amplify/storage/resource.ts
  amplify/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: 📦️ Chore

#14 📦️ Chore(#7): Husky 세팅
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: 📦️ Chore

#16 📦 Chore: 배포 세팅
  .eslintrc.json
  .prettierrc.json
  amplify.yml
  next.config.js
  next.config.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 📦️ Chore

#17 📦 Chore: 라이브러리 업데이트
  package.json
  pnpm-lock.yaml
Labels: 📦️ Chore

#19 📦 Chore(#18): Drawer 공통 컴포넌트 가져오기
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/file.svg
  public/gifs/loading-spinner.svg
  public/globe.svg
  public/icons/icon-arrow-down.svg
  public/icons/icon-check-bold.svg
  public/icons/icon-check.svg
  public/icons/icon-checkbox-active.svg
  public/icons/icon-checkbox.svg
  public/icons/icon-chevron-left.svg
  public/icons/icon-chevron-right.svg
  public/icons/icon-dashboard.svg
  public/icons/icon-delete-button.svg
  public/icons/icon-double-right-arrow.svg
  public/icons/icon-drawer-bar.svg
  public/icons/icon-equipment.svg
  public/icons/icon-hamburger.svg
  public/icons/icon-kebab.svg
  public/icons/icon-meeting.svg
  public/icons/icon-modal-alert.svg
  public/icons/icon-order.svg
  public/icons/icon-person.svg
  public/icons/icon-plus.svg
  public/icons/icon-search.svg
  public/icons/icon-seats.svg
  public/icons/icon-settings.svg
  public/icons/icon-team.svg
  public/icons/icon-x-button.svg
  public/images/codeit-inactive.svg
  public/images/codeit-resources.svg
  public/images/codeit.svg
  public/images/default-profile.png
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/components/commons/Drawer/index.stories.tsx
  src/components/commons/Drawer/index.tsx
Labels: 📦️ Chore

#20 📦️ Chore(#15): Button 컴포넌트
  .prettierrc.json
  package.json
  src/components/commons/Button/index.stories.tsx
  src/components/commons/Button/index.tsx
Labels: 📦️ Chore

#25 📦 Chore: font 및 tailwind 세팅
  src/styles/globals.css
  tailwind.config.ts
Labels: 📦️ Chore

#26 📦 Chore(#24): Profile Image & ErrorBoundary & Tab
  .eslintrc.json
  .prettierrc.json
  .storybook/preview.ts
  package.json
  src/components/commons/Button/index.stories.tsx
  src/components/commons/ErrorBoundary/index.tsx
  src/components/commons/ProfileImage/index.stories.tsx
  src/components/commons/ProfileImage/index.tsx
  src/components/commons/Tab/index.stories.tsx
  src/components/commons/Tab/index.tsx
  src/components/commons/Tab/useTabDrag.ts
  src/lib/api/storage.ts
  src/pages/_app.tsx
  src/styles/globals.css
Labels: 📦️ Chore

#27 Chore(#21): 바텀시트, 토스트, storybook svgr관련 세팅
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/components/commons/BottomSheet/BackgroundOverlay.tsx
  src/components/commons/BottomSheet/BottomSheetOpenButton.tsx
  src/components/commons/BottomSheet/animations.ts
  src/components/commons/BottomSheet/index.stories.tsx
  src/components/commons/BottomSheet/index.tsx
  src/components/commons/BottomSheet/useBottomSheet.ts
  src/components/commons/Tab/index.stories.tsx
  src/components/commons/Toast/ToastProvider.tsx
  src/components/commons/Toast/index.stories.tsx
  src/components/commons/Toast/index.tsx
  src/hooks/useToast.ts
  src/pages/_app.tsx
  src/store/toastAtom.ts
Labels: 📦️ Chore

#35 📦️ Chore(#22): Badge, Dropdown, Popover Migration
  src/components/commons/Badge/index.stories.tsx
  src/components/commons/Badge/index.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/MembersSelectDropdown/index.stories.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/MembersSelectDropdown/index.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/TeamsSelectDropdown/index.stories.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/TeamsSelectDropdown/index.tsx
  src/components/commons/Dropdown/Toggle/MeetingRoomToggle.tsx
  src/components/commons/Dropdown/Toggle/OrderToggle.tsx
  src/components/commons/Dropdown/Toggle/RoleToggle.tsx
  src/components/commons/Dropdown/Toggle/TimeToggle.tsx
  src/components/commons/Dropdown/dropdownType.ts
  src/components/commons/Dropdown/index.stories.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/commons/Popover/index.stories.tsx
  src/components/commons/Popover/index.tsx
  src/components/commons/Toast/ToastProvider.tsx
  src/components/commons/Toast/index.stories.tsx
  src/components/commons/Toast/index.tsx
  src/constants/dropdownConstants.ts
  src/hooks/useDropdown.ts
Labels: 📦️ Chore

#36 📦 Chore: MobileSizeWatcher, useIsMobile 가져오기
  src/components/commons/MobileSizeWatcher/index.tsx
  src/hooks/useIsMobile.ts
  src/pages/_app.tsx
  src/store/mobileAtom.ts
Labels: 📦️ Chore

#38 📦 Chore: Sign-In Page
  package.json
  pnpm-lock.yaml
  src/components/pages/sign-in/SignInForm.tsx
  src/constants/error-message/user.ts
  src/lib/utils/autoAuthUser.ts
  src/lib/zod-schema/user.ts
  src/pages/_app.tsx
  src/pages/sign-in.tsx
  src/store/authUserAtom.ts
  tsconfig.json
Labels: 📦️ Chore

#44 📦️ Chore(#40): Layout Migration
  src/components/Layout/NavigationBar/NavOptionList.tsx
  src/components/Layout/NavigationBar/index.tsx
  src/components/Layout/index.tsx
  src/pages/_app.tsx
  src/pages/fonts/GeistMonoVF.woff
  src/pages/fonts/GeistVF.woff
Labels: 📦️ Chore

#42 ✨ Feat(#44): api 관련 함수 마이그레이션 & 예약 구글캘린더 작업중
  amplify/data/resource.ts
  package.json
  pnpm-lock.yaml
  src/lib/api/amplify/helper.ts
  src/lib/api/amplify/reservation/common.ts
  src/lib/api/amplify/reservation/index.ts
  src/lib/api/amplify/reservation/seat.ts
  src/lib/api/amplify/reservation/utils.ts
  src/lib/api/amplify/resource/index.ts
  src/lib/api/amplify/resource/utils.ts
  src/lib/api/amplify/team/index.ts
  src/lib/api/amplify/team/utils.ts
  src/lib/api/amplify/user/index.ts
  src/lib/api/amplify/user/utils.ts
  src/lib/api/googleCalendar/helper.ts
  src/lib/api/googleCalendar/index.ts
  src/lib/types/calendar.d.ts
  src/lib/utils/timeUtils.ts
  src/pages/api/hello.ts
  src/pages/api/reservation/[reservationId]/index.ts
  src/pages/api/reservation/create.ts
  src/pages/api/reservation/index.ts
  src/pages/index.tsx
Labels: ✨ Feat

#45 🐛 Fix: 유저 정보 추가
  src/components/Layout/index.tsx
  src/components/commons/ProfileImage/index.tsx
  src/styles/globals.css
Labels: 🚑️ Fix

#52 📦 Chore(#50): mypage Migration
  src/components/pages/mypage/AccountSection.tsx
  src/components/pages/mypage/MobileProfileSectionSkeleton.tsx
  src/components/pages/mypage/PasswordChangeSection.tsx
  src/components/pages/mypage/ProfileSection.tsx
  src/components/pages/mypage/ProfileSectionSkeleton.tsx
  src/components/pages/mypage/SettingsLinks.tsx
  src/pages/mypage.tsx
Labels: 📦️ Chore

#53 📦 Chore(#43): 회의실 예약 페이지 마이그레이션
  package.json
  pnpm-lock.yaml
  src/components/pages/meeting-rooms/Layout.tsx
  src/components/pages/meeting-rooms/MeetingRoomsSkeleton.tsx
  src/components/pages/meeting-rooms/ReservationForm.tsx
  src/components/pages/meeting-rooms/RoomSelection.tsx
  src/components/pages/meeting-rooms/ScrollProvider.tsx
  src/components/pages/meeting-rooms/ThirtyMinutesTimeBox.tsx
  src/components/pages/meeting-rooms/TimeLine.tsx
  src/components/pages/meeting-rooms/TimeText.tsx
  src/components/pages/meeting-rooms/Tooltip.tsx
  src/components/pages/meeting-rooms/context/conflictReservation.ts
  src/components/pages/meeting-rooms/context/pickedDate.ts
  src/components/pages/meeting-rooms/context/pickedReservation.ts
  src/components/pages/meeting-rooms/context/scroll.ts
  src/components/pages/meeting-rooms/hooks/useGetReservations.ts
  src/components/pages/meeting-rooms/hooks/useReservationAction.ts
  src/components/pages/meeting-rooms/hooks/useReservationSchema.ts
  src/components/pages/meeting-rooms/hooks/useReservationTimeValidation.ts
  src/components/pages/meeting-rooms/index.tsx
  src/components/pages/meeting-rooms/modals/CreateRoomReservationModal.tsx
  src/components/pages/meeting-rooms/modals/DeleteRoomReservationModal.tsx
  src/components/pages/meeting-rooms/modals/UpdateRoomReservationModal.tsx
  src/components/pages/meeting-rooms/types/TimeLinetypes.ts
  src/components/pages/meeting-rooms/useTimeSlot.tsx
  src/constants/timeSlot.ts
  src/lib/utils/getDaysUntilEndOfMonth.ts
  src/pages/meeting-rooms.tsx
  src/store/isOpenDrawerAtom.ts
  src/store/reservationAtom.ts
  src/store/tempSelectedTimeAtom.ts
  src/store/todayDateAtom.ts
  src/utils/createTime.ts
  src/utils/sendMail.ts
Labels: 📦️ Chore

#54 📦️ Chore(#51): 회의실 관리 페이지 Migration
  src/components/commons/Error/index.tsx
  src/components/commons/Modal/index.tsx
  src/components/pages/admin/meeting-rooms/AddMeetingRoomTypeModal.tsx
  src/components/pages/admin/meeting-rooms/AdminMeetingRoomSkeleton.tsx
  src/components/pages/admin/meeting-rooms/EmptyMeetingRooms.tsx
  src/components/pages/admin/meeting-rooms/MeetingRoomList.tsx
  src/components/pages/meeting-rooms/modals/CreateRoomReservationModal.tsx
  src/components/pages/meeting-rooms/modals/DeleteRoomReservationModal.tsx
  src/components/pages/meeting-rooms/modals/UpdateRoomReservationModal.tsx
  src/lib/zod-schema/meetingRooms.ts
  src/pages/admin/meeting-rooms.tsx
Labels: 📦️ Chore

#58 📦 Chore(#56): 비밀번호 찾기 페이지 마이그레이션
  src/components/pages/find-password/components/FindPasswordForm.tsx
  src/components/pages/find-password/components/StepTwo.tsx
  src/pages/_app.tsx
  src/pages/find-password.tsx
Labels: 📦️ Chore

#62 📦 Chore(#61): 팀 관리 페이지
  src/components/commons/Modal/index.tsx
  src/components/pages/admin/teams/AddTeamModal.tsx
  src/components/pages/admin/teams/DeleteTeamModal.tsx
  src/components/pages/admin/teams/TeamList.tsx
  src/components/pages/admin/teams/UpdateTeamModal.tsx
  src/lib/zod-schema/team.ts
  src/pages/admin/teams.tsx
Labels: 📦️ Chore

#63 📦 Chore(#57): 멤버 관리 Page Migration
  src/components/Layout/NavigationBar/index.tsx
  src/components/commons/Modal/index.tsx
  src/components/pages/admin/members/DeleteMemberModal.tsx
  src/components/pages/admin/members/MemberAddDrawer.tsx
  src/components/pages/admin/members/MemberEditDrawer.tsx
  src/components/pages/admin/members/MemberForm.tsx
  src/components/pages/admin/members/MemberList.tsx
  src/components/pages/admin/members/MemberProfileImage.tsx
  src/components/pages/admin/members/MemberTap.tsx
  src/components/pages/admin/members/hooks/useUploadImage.ts
  src/pages/admin/members.tsx
Labels: 📦️ Chore

#64 📦 Chore(#59): 대시보드 페이지 마이그레이션
  src/components/pages/dashboard/RESOURCE_INFO.ts
  src/components/pages/dashboard/components/EmptyReservation.tsx
  src/components/pages/dashboard/components/MyReservation.tsx
  src/components/pages/dashboard/components/ReservationCard.tsx
  src/components/pages/dashboard/hooks/useDashboardAction.ts
  src/components/pages/dashboard/hooks/useGetUserReservation.ts
  src/components/pages/meeting-rooms/index.tsx
  src/components/pages/meeting-rooms/types/TimeLinetypes.ts
  src/constants/common.ts
  src/hooks/useAutoUpdateDate.ts
  src/hooks/useIsOngoing.ts
  src/lib/api/amplify/helper.ts
  src/pages/index.tsx
Labels: 📦️ Chore, 🔨 Refactor

#66 ✨ Feat(#65): 구글 로그인 임시 구현
  amplify/auth/resource.ts
  src/components/Layout/index.tsx
  src/lib/api/amplify/helper.ts
  src/pages/sign-in.tsx
Labels: ✨ Feat, ✅ Test, 🌐 Web

#75 🐛 fix: 미팅룸 로직 수정
  src/components/Layout/ScrollProvider.tsx
  src/components/Layout/index.tsx
  src/components/pages/dashboard/components/MyReservation.tsx
  src/components/pages/dashboard/components/ReservationCard.tsx
  src/components/pages/meeting-rooms/Layout.tsx
  src/components/pages/meeting-rooms/components/MeetingRoomsSkeleton.tsx
  src/components/pages/meeting-rooms/components/ReservationForm.tsx
  src/components/pages/meeting-rooms/components/RoomSelection.tsx
  src/components/pages/meeting-rooms/components/TimeLine/TIME_SLOT_STLYE.ts
  src/components/pages/meeting-rooms/components/TimeLine/ThirtyMinutesTimeBox.tsx
  src/components/pages/meeting-rooms/components/TimeLine/TimeLine.tsx
  src/components/pages/meeting-rooms/components/TimeLine/TimeLineType.ts
  src/components/pages/meeting-rooms/components/TimeLine/TimeText.tsx
  src/components/pages/meeting-rooms/components/TimeLine/Tooltip.tsx
  src/components/pages/meeting-rooms/components/index.ts
  src/components/pages/meeting-rooms/context/conflictReservation.ts
  src/components/pages/meeting-rooms/context/pickedReservationGroup.ts
  src/components/pages/meeting-rooms/hooks/useGroupManager.ts
  src/components/pages/meeting-rooms/hooks/useReservationAction.ts
  src/components/pages/meeting-rooms/hooks/useReservationSchema.ts
  src/components/pages/meeting-rooms/hooks/useTimeSlot.tsx
  src/components/pages/meeting-rooms/index.tsx
  src/components/pages/seats/Header.tsx
  src/components/pages/seats/SeatGrid.tsx
  src/lib/utils/timeUtils.ts
  src/pages/index.tsx
  src/pages/meeting-rooms.tsx
  src/pages/seats.tsx
  src/store/reservationAtom.ts
  src/store/scrollAtom.ts
  src/store/tempSelectedTimeAtom.ts
Labels: 🚑️ Fix, 🔨 Refactor

#76 ✨ Feat: 오픈 그래프 추가
  public/images/codeit_image.png
  src/components/pages/admin/seats/Header.tsx
  src/components/pages/seats/Header.tsx
  src/pages/_document.tsx
Labels: ✨ Feat

#71 📦 Chore(#70): svgr 아이콘 기본 크기 세팅
  next.config.js
Labels: 📦️ Chore

#80 ✨ Feat(#77): next-auth로 구글 로그인 구현
  amplify/data/resource.ts
  package.json
  pnpm-lock.yaml
  src/components/Layout/index.tsx
  src/components/pages/mypage/AccountSection.tsx
  src/lib/api/amplify/user/index.ts
  src/lib/types/next-auth.d.ts
  src/lib/utils/googleUserUtils.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/sign-in.tsx
  src/utils/cookieUtils.ts
Labels: ✨ Feat

#84 🐛 Fix(#83): 배포 환경에서 구글 로그인 안되는 현상 수정
  amplify.yml
  amplify/auth/resource.ts
  amplify/data/resource.ts
  src/pages/api/auth/[...nextauth].ts
Labels: 🚑️ Fix

#86 ✨ Feat(#82): Favicon 및 Title 적용 & Navigation Bar 수정
  src/components/Layout/NavigationBar/index.tsx
  src/components/commons/Popover/index.tsx
  src/pages/_app.tsx
Labels: ✨ Feat

#87 ✨ Feat(#85): 접근 권한 iam으로 변경
  amplify/data/resource.ts
Labels: ✨ Feat

#88 Refactor(#81): 타임라인 스타일 수정
  src/components/pages/meeting-rooms/components/ReservationForm.tsx
  src/components/pages/meeting-rooms/components/TimeLine/TIME_SLOT_STLYE.ts
  src/components/pages/meeting-rooms/components/TimeLine/ThirtyMinutesTimeBox.tsx
  src/components/pages/meeting-rooms/components/index.ts
  src/components/pages/meeting-rooms/hooks/useReservationSchema.ts
  src/components/pages/meeting-rooms/hooks/useTimeSlot.tsx
  src/components/pages/meeting-rooms/index.tsx
  src/pages/meeting-rooms.tsx
Labels: 💄 Design, 🔨 Refactor

#92 ✨ Feat(#74): 로그인 후 로직 수정
  src/components/Layout/index.tsx
  src/lib/api/amplify/user/index.ts
  src/lib/utils/googleUserUtils.ts
  src/middleware.ts
  src/pages/api/auth/syncUserInfo.ts
  src/pages/sign-in.tsx
Labels: ✨ Feat

#90 💄 Design(#89): SVGR Image 컴포넌트로 변경
  src/components/Layout/NavigationBar/index.tsx
  src/pages/404.tsx
  src/pages/sign-in.tsx
Labels: 💄 Design

#99 ✨ Feat(#97): 구글 워크스페이스 프로필 이미지 가져오기
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/profilePhoto.ts
  src/pages/api/auth/syncUserInfo.ts
Labels: ✨ Feat

#103 ♻️ Refactor(#100): 로그인 후 에러 처리 및 로컬에서 두 번 데이터 생성되는 현상 해결
  src/components/Layout/index.tsx
  src/lib/api/amplify/user/index.ts
  src/pages/api/auth/syncUserInfo.ts
Labels: 🔨 Refactor

#102 🔨 Refactor(#101): 좌석 페이지 정렬 로직 수정
  src/components/pages/admin/seats/Loading.tsx
  src/components/pages/admin/seats/SeatButton.tsx
  src/components/pages/admin/seats/SeatGrid.tsx
  src/components/pages/admin/seats/hooks/useGetAllSeatsData.ts
  src/components/pages/seats/Loading.tsx
  src/components/pages/seats/SeatButton.tsx
  src/components/pages/seats/hooks/useGetAllSeatsData.ts
  src/lib/api/amplify/helper.ts
  src/pages/api/admin/seats/index.ts
  src/pages/api/seats/index.ts
Labels: 🔨 Refactor

#105 ♻️ Refactor(#93): 멤버 관리 페이지 - 멤버 추가, 수정, 삭제 구현
  src/components/commons/Input/index.tsx
  src/components/pages/admin/members/DeleteMemberModal.tsx
  src/components/pages/admin/members/MemberAddDrawer.tsx
  src/components/pages/admin/members/MemberEditDrawer.tsx
  src/components/pages/admin/members/MemberForm.tsx
  src/components/pages/admin/members/MemberProfileImage.tsx
  src/lib/api/amplify/user/index.ts
  src/styles/globals.css
Labels: 🔨 Refactor

#115 💄 Design(#96): Dropdown 애니메이션 적용 및 Input과 스타일 통일
  src/components/commons/Dropdown/MultiSelectDropdown/MembersSelectDropdown/index.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/TeamsSelectDropdown/index.tsx
  src/components/commons/Dropdown/Toggle/MeetingRoomToggle.tsx
  src/components/commons/Dropdown/Toggle/TimeToggle.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/commons/Popover/index.tsx
  src/components/pages/admin/seats/EditDrawer/UserSelect.tsx
  src/constants/dropdownConstants.ts
  src/styles/globals.css
Labels: 💄 Design, ✨ Feat

#114 📦 Chore(#107): 불필요한 코드 제거 및 로그인 페이지 디자인
  public/icons/icon-google.svg
  public/images/codeit-resources.svg
  public/images/codeit.svg
  src/components/pages/admin/members/MemberList.tsx
  src/components/pages/admin/members/hooks/useUploadImage.ts
  src/components/pages/find-password/components/FindPasswordForm.tsx
  src/components/pages/find-password/components/StepTwo.tsx
  src/components/pages/mypage/AccountSection.tsx
  src/components/pages/sign-in/SignInForm.tsx
  src/constants/error-message/user.ts
  src/lib/utils/autoAuthUser.ts
  src/lib/utils/sendMail.ts
  src/lib/zod-schema/user.ts
  src/pages/find-password.tsx
  src/pages/sign-in.tsx
  src/store/authUserAtom.ts
Labels: 💄 Design, 📦️ Chore

#111 ✨ Feat(#108): 로그인 시, 프로필 이미지 받아오기
  src/components/Layout/index.tsx
  src/components/pages/admin/members/MemberAddDrawer.tsx
  src/lib/api/amplify/user/index.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/profilePhoto.ts
  src/pages/api/auth/syncUserInfo.ts
Labels: 🔨 Refactor, ✨ Feat

#119 🔥 Remove: Image upload 기능 제거
  src/components/commons/ProfileImage/index.tsx
  src/components/pages/mypage/ProfileSection.tsx
  src/lib/api/amplify/storage.ts
Labels: 📦️ Chore

#116 🚑️ Fix(#91): 회의실 예약 페이지 버그 수정
  src/components/Layout/NavigationBar/index.tsx
  src/components/commons/Drawer/index.tsx
  src/components/commons/Tab/useTabDrag.ts
  src/components/pages/meeting-rooms/Layout.tsx
  src/components/pages/meeting-rooms/components/ReservationForm.tsx
  src/components/pages/meeting-rooms/components/RoomSelection.tsx
  src/components/pages/meeting-rooms/components/TimeLine/ThirtyMinutesTimeBox.tsx
  src/components/pages/meeting-rooms/components/TimeLine/getTimeSlotStyle.ts
  src/components/pages/meeting-rooms/components/TimeLine/index.tsx
  src/components/pages/meeting-rooms/hooks/useReservationAction.ts
  src/components/pages/meeting-rooms/hooks/useReservationSchema.ts
  src/lib/utils/timeUtils.ts
  src/pages/meeting-rooms.tsx
  src/store/isOpenDrawerAtom.ts
Labels: 🚑️ Fix, 🔨 Refactor

#126 ✨ Feat(#117): refresh token 갱신 로직 추가
  src/pages/api/auth/[...nextauth].ts
Labels: ✨ Feat

#124 🐛 Fix(#120): 다른 사람 회의 안가져와지는 오류 수정
  src/components/pages/dashboard/hooks/useGetUserReservation.ts
  src/components/pages/meeting-rooms/hooks/useReservationAction.ts
  src/pages/api/reservation/[reservationId]/index.ts
  src/pages/api/reservation/helper.ts
Labels: 🚑️ Fix

#121 💄 Design(#106): 멤버 관리 페이지 UI
  src/components/commons/Badge/index.tsx
  src/components/commons/Modal/index.tsx
  src/components/pages/admin/members/MemberCard.tsx
  src/components/pages/admin/members/MemberList.tsx
  src/components/pages/admin/members/MemberSkeleton.tsx
  src/components/pages/admin/members/form/DeleteMemberModal.tsx
  src/components/pages/admin/members/form/MemberAddDrawer.tsx
  src/components/pages/admin/members/form/MemberEditDrawer.tsx
  src/components/pages/admin/members/form/MemberForm.tsx
  src/lib/zod-schema/user.ts
  src/pages/admin/members.tsx
  tailwind.config.ts
Labels: 💄 Design

#128 🐛 fix(#127): API 도메인 주소 오류 수정
  src/lib/api/helper.ts
Labels: 🚑️ Fix

#125 🐛 Fix(#123): 스크롤 오류 수정
  src/components/Layout/Scroll/ScrollContainer.tsx
  src/components/Layout/Scroll/ScrollProvider.tsx
  src/components/Layout/Scroll/useScrollContainer.ts
  src/components/pages/admin/seats/SeatGrid.tsx
  src/components/pages/dashboard/components/MyReservation.tsx
  src/components/pages/meeting-rooms/Layout.tsx
  src/components/pages/meeting-rooms/components/ReservationForm.tsx
  src/components/pages/meeting-rooms/components/RoomSelection.tsx
  src/components/pages/meeting-rooms/components/TimeLine/index.tsx
  src/components/pages/seats/SeatGrid.tsx
  src/pages/meeting-rooms.tsx
Labels: 🚑️ Fix

#136 💄 Design(#134): Dropdown 스타일 변경
  src/components/Layout/NavigationBar/index.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/MembersSelectDropdown/index.tsx
  src/components/commons/Dropdown/MultiSelectDropdown/TeamsSelectDropdown/index.tsx
  src/components/pages/admin/seats/EditDrawer/UserSelect.tsx
  src/components/pages/mypage/ProfileSection.tsx
Labels: 💄 Design

#131 ♻️ Refactor(#122): api route 사용하여 유저, 팀 리팩토링
  src/components/pages/admin/members/MemberCard.tsx
  src/components/pages/admin/teams/DeleteTeamModal.tsx
  src/lib/api/amplify/team/index.ts
  src/lib/api/amplify/team/utils.ts
  src/lib/api/amplify/user/index.ts
  src/lib/api/amplify/user/utils.ts
  src/pages/api/team/index.ts
  src/pages/api/users/index.ts
Labels: 🔨 Refactor

#133 ✨ Feat(#113): 구글 리소스 아이디 등록
  public/images/resource-id-step1.png
  public/images/resource-id-step2.png
  public/images/resource-id-step3.png
  src/components/pages/admin/meeting-rooms/AddMeetingRoomTypeModal.tsx
  src/components/pages/admin/meeting-rooms/GoogleResourceIDPopover.tsx
  src/components/pages/admin/meeting-rooms/MeetingRoomList.tsx
  src/components/pages/admin/seats/Loading.tsx
  src/hooks/useClickOutside.ts
  src/lib/api/amplify/resource/index.ts
  src/lib/zod-schema/meetingRooms.ts
  src/pages/admin/meeting-rooms.tsx
Labels: ✨ Feat

#137 ✨ Feat(#135): 신규 유저 온보딩 페이지 구현
  src/components/Layout/index.tsx
  src/pages/_app.tsx
  src/pages/api/auth/syncUserInfo.ts
  src/pages/on-boarding.tsx
Labels: ✨ Feat

#141 ✨ Feat(#140): mypage 디자인 변경
  src/components/commons/Button/index.tsx
  src/components/pages/mypage/LogOutButton.tsx
  src/components/pages/mypage/MobileProfileSectionSkeleton.tsx
  src/components/pages/mypage/ProfileSection.tsx
  src/components/pages/mypage/ProfileSectionSkeleton.tsx
  src/components/pages/mypage/SettingsLinks.tsx
  src/pages/mypage.tsx
Labels: 💄 Design, ✨ Feat

#162 📦 Chore: Merge from Test Branch
  package.json
  pnpm-lock.yaml
  public/icons/icon-checkbox-disabled.svg
  src/components/commons/Drawer/index.tsx
  src/components/commons/Drawer/usePreventScroll.ts
  src/components/commons/Drawer/useRouteChangeCloseDrawer.ts
  src/components/commons/Dropdown/MultiSelectDropdown/MembersSelectDropdown/index.tsx
  src/components/commons/Toast/index.tsx
  src/components/pages/admin/members/MemberList.tsx
  src/components/pages/admin/members/form/DeleteMemberModal.tsx
  src/components/pages/admin/members/form/MemberAddDrawer.tsx
  src/components/pages/admin/members/form/MemberEditDrawer.tsx
  src/components/pages/admin/members/store/selectUser.ts
  src/components/pages/admin/seats/EditDrawer/index.tsx
  src/components/pages/admin/seats/SeatButton.tsx
  src/components/pages/admin/seats/SeatGrid.tsx
  src/components/pages/admin/seats/context/drawer.tsx
  src/components/pages/admin/seats/hooks/useSeatsAction.ts
  src/components/pages/meeting-rooms/hooks/useReservationAction.ts
  src/components/pages/mypage/SettingsLinks.tsx
  src/lib/api/googleCalendar/helper.ts
  src/pages/admin/members.tsx
  src/pages/api/reservation/helper.ts
Labels: 📦️ Chore

#161 📝 Docs(#160): 리드미 작성
  README.md
  public/readme/back.png
  public/readme/front.png
  public/readme/image1.png
  public/readme/image10.png
  public/readme/image2.png
  public/readme/image3.png
  public/readme/image4.png
  public/readme/image5.png
  public/readme/image6.png
  public/readme/image7.png
  public/readme/image8.png
  public/readme/image9.png
  public/readme/main.png
Labels: 📚 Docs

#171 📦 Chore: Merge from Test Branch
  package.json
  pnpm-lock.yaml
  src/components/pages/meeting-rooms/components/ReservationForm.tsx
  src/components/pages/meeting-rooms/hooks/useReservationAction.ts
Labels: 📦️ Chore

#177 🐛 Fix(#175): 멤버 목록 모바일에서 반응형 깨지는 현상
  src/components/pages/admin/members/MemberCard.tsx
Labels: 🚑️ Fix, 💄 Design

#185 🐛 Fix: 좌석 페이지 예약 데이터 못 가져오는 이슈
  src/lib/api/amplify/reservation/seat.ts
  src/pages/api/admin/seats/index.ts
  src/pages/api/seats/index.ts
Labels: 🚑️ Fix
